with open('config/mapping_config.yaml', 'w', encoding='utf-8') as f:
    f.write('mapping:\n')
    f.write('  confidence_thresholds:\n')
    f.write('    high: 0.8\n')
    f.write('    medium: 0.5\n')
    f.write('    low: 0.3\n')
    f.write('  strategies:\n')
    f.write('    - direct_lookup\n')
    f.write('    - translation_based\n')
    f.write('    - fuzzy_matching\n')
    f.write('  validation:\n')
    f.write('    name_similarity_threshold: 60\n')
    f.write('    combination_drug_penalty: 0.7\n')
    f.write('    form_mismatch_penalty: 0.8\n')
    f.write('    max_alternatives: 5\n')
    f.write('\n')
    f.write('output:\n')
    f.write('  formats: [excel, json]\n')
    f.write('  include_alternatives: true\n')
    f.write('  batch_size: 100\n')
    f.write('\n')
    f.write('processing:\n')
    f.write('  max_workers: 4\n')
    f.write('  chunk_size: 500\n')
print('Mapping config created!')
